// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
	"encoding/json"
	"time"
)

type Artifact struct {
	ID             int32
	UserID         int32
	Name           string
	TotalParts     int16
	CompletedParts int16
	Metadata       json.RawMessage
	CreatedAt      time.Time
}

type ArtifactPart struct {
	ID         int32
	ArtifactID int32
	SessionID  sql.NullInt32
	PartIndex  int16
	PartType   sql.NullString
	Rarity     sql.NullString
	Metadata   json.RawMessage
	CreatedAt  time.Time
}

type FocusSession struct {
	ID              int32
	UserID          int32
	TaskID          sql.NullInt32
	StartedAt       time.Time
	EndedAt         sql.NullTime
	DurationMinutes sql.NullInt32
	Completed       bool
	CreatedAt       time.Time
}

type Task struct {
	ID          int32
	UserID      int32
	Title       string
	Description sql.NullString
	Category    sql.NullString
	Priority    int16
	IsCompleted bool
	DueDate     sql.NullTime
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type User struct {
	ID        int32
	Email     string
	Password  string
	CreatedAt time.Time
}
